### ISSUE TITLE
testArg_subresource_Text fails on 3.13.1; additional errors on 3.13.1, 3.11.9 [macOS]

### ISSUE THREAD

**Issue by PikalaxALT** [PokeAPI/pokebase#62]
Operating system: macOS Sequoia 15.2, M3 chip, 2024

To reproduce:

```
python -m venv ~/pokebase-env
source ~/pokebase-env/bin/activate
# export PATH=$HOME/pokebase-env/bin:$PATH
python -m pip install -U pip
git clone https://github.com/PokeAPI/pokebase
cd pokebase
# git checkout 1.4.0  # also observed on d40c95ce41e62e1d97cefa4ad4ee8d0500c423d9
python -m pip install -e .
python -m pip install hypothesis
python -m tests
```

Expectation: 0 failures

Observation (on Python 3.13.1):
```
======================================================================
FAIL: testArg_subresource_Text (tests.test_module_api.TestFunction_get_data.testArg_subresource_Text)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/mock.py", line 1420, in testArg_subresource_Text
    def patched(*args, **keywargs):
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pikalaxalt/pokebase-env/lib/python3.13/site-packages/hypothesis/core.py", line 1787, in wrapped_test
    raise the_error_hypothesis_found
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/mock.py", line 1424, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/pikalaxalt/pokebase/tests/test_module_api.py", line 106, in testArg_subresource_Text
    self.assertIsNotNone(api.get_data(endpoint, resource_id, subresource).get('version_details'))
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: unexpectedly None
Falsifying example: testArg_subresource_Text(
    <tests.test_module_api.TestFunction_get_data testMethod=testArg_subresource_Text>,
    endpoint='ability',
    resource_id=1,
    subresource='',
)
Explanation:
    These lines were always and only run by failing examples:
        /Users/pikalaxalt/pokebase/pokebase/api.py:37
        /opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shelve.py:114
```

Additionally the following errors are observed in both this version and under python 3.11.9:

```
======================================================================
ERROR: testEnv_CacheFileNotFound (tests.test_module_cache.TestFunction_load.testEnv_CacheFileNotFound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pikalaxalt/pokebase/tests/test_module_cache.py", line 112, in testEnv_CacheFileNotFound
    resource_id=integers(min_value=1))
        ^^^^^^^
  File "/Users/pikalaxalt/pokebase-env/lib/python3.13/site-packages/hypothesis/core.py", line 1787, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/pikalaxalt/pokebase/tests/test_module_cache.py", line 116, in testEnv_CacheFileNotFound
    os.remove(cache.API_CACHE)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pikalaxalt/pokebase/testing/api.cache'
Falsifying example: testEnv_CacheFileNotFound(
    self=<tests.test_module_cache.TestFunction_load testMethod=testEnv_CacheFileNotFound>,
    endpoint='ability',
    resource_id=1,
)

======================================================================
ERROR: testEnv_CacheFileNotFound (tests.test_module_cache.TestFunction_save.testEnv_CacheFileNotFound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pikalaxalt/pokebase/tests/test_module_cache.py", line 59, in testEnv_CacheFileNotFound
    endpoint=sampled_from(ENDPOINTS),
        ^^^^^^^
  File "/Users/pikalaxalt/pokebase-env/lib/python3.13/site-packages/hypothesis/core.py", line 1787, in wrapped_test
    raise the_error_hypothesis_found
  File "/Users/pikalaxalt/pokebase/tests/test_module_cache.py", line 63, in testEnv_CacheFileNotFound
    os.remove(cache.API_CACHE)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pikalaxalt/pokebase/testing/api.cache'
Falsifying example: testEnv_CacheFileNotFound(
    self=<tests.test_module_cache.TestFunction_save testMethod=testEnv_CacheFileNotFound>,
    data={'': ''},
    endpoint='ability',
    resource_id=1,
)

======================================================================
ERROR: testEnv_CacheDirNotFound (tests.test_module_cache.TestFunction_set_cache.testEnv_CacheDirNotFound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pikalaxalt/pokebase/tests/test_module_cache.py", line 172, in testEnv_CacheDirNotFound
    os.rmdir(cache.CACHE_DIR)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
OSError: [Errno 66] Directory not empty: '/Users/pikalaxalt/pokebase/testing'
```

**Comment by Naramsim** [comment]
hi @GregHilmes, could you check this issue?

**Comment by joaoprp** [comment]
@PikalaxALT @Naramsim I tried to follow the same steps to reproduce, but I see a different error, mostly because it isn't properly installing dependencies.

The steps I took on a Mac M2 Pro using macOS Sequoia (26.5.1):

```zsh

# I normally use ssh to clone, but it can https
git clone git@github.com:PokeAPI/pokebase.git

git checkout 1.4.0

cd pokebase

python3 -m venv .venv

# I use fish, but if you use zsh (mac's default), you can run
# `source .venv/bin/activate`
source .venv/bin/activate.fish

pip install -U pip

pip install -r requirements/test.txt

python -m tests
```

results as follows:

```zsh
(.venv) joaoprp@wadjet ~/p/pokebase (1.4.0)> python -m tests
.............................................You can add @seed(15534538010232236646139178681817137212) to this test to reproduce this failure.
s....................................................................
----------------------------------------------------------------------
Ran 114 tests in 6.988s

OK (skipped=1)
```

I would recommend try to pip install the requirements on the requirements folder directly, rather than trying to install them manually. `hypotesis` is already a requirement on the `tests.txt`, so you wouldn't even need to install it separately as it's listed on this steps to reproduce.
